using System.ComponentModel;

namespace WPFDevelopers.Controls
{
    public enum PackIconKind
    {
        [Description("WD.CheckMarkGeometry")] CheckMark,
        [Description("WD.ChevronUpGeometry")] ChevronUp,
        [Description("WD.ChevronDownGeometry")] ChevronDown,
        [Description("WD.BlackoutGeometry")] Blackout,
        [Description("WD.PreviousGeometry")] Previous,
        [Description("WD.NextGeometry")] Next,
        [Description("WD.DatePickerGeometry")] DatePicker,
        [Description("WD.ChevronRightGeometry")] ChevronRight,
        [Description("WD.SortArrowGeometry")] SortArrow,
        [Description("WD.WindowMaximizeGeometry")] WindowMaximize,
        [Description("WD.WindowRestoreGeometry")] WindowRestore,
        [Description("WD.WindowCloseGeometry")] WindowClose,
        [Description("WD.InformationGeometry")] Information,
        [Description("WD.WarningGeometry")] Warning,
        [Description("WD.QuestionGeometry")] Question,
        [Description("WD.ErrorGeometry")] Error,
        [Description("WD.SmileyOutlineGeometry")] SmileyOutline,
        [Description("WD.BusGeometry")] Bus,
        [Description("WD.FriendGeometry")] Friend,
        [Description("WD.BuildingRegularGeometry")] BuildingRegular,
        [Description("WD.AlarmClockGeometry")] AlarmClock,
        [Description("WD.FlagGeometry")] Flag,
        [Description("WD.CircularGeometry")] Circular,
        [Description("WD.AddGeometry")] Add,
        [Description("WD.ChatLeftGeometry")] ChatLeft,
        [Description("WD.ChatRightGeometry")] ChatRight,
        [Description("WD.StarGeometry")] Star,
        [Description("WD.CompleteGeometry")] Complete,
        [Description("WD.CancelGeometry")] Cancel,
        [Description("WD.SaveGeometry")] Save,
        [Description("WD.MenuGeometry")] Menu,
        [Description("WD.SectorGeometry")] Sector,
        [Description("WD.ReplaceGeometry")] Replace,
        [Description("WD.AudioOneGeometry")] AudioOne,
        [Description("WD.AudioTwoGeometry")] AudioTwo,
        [Description("WD.AudioThreeGeometry")] AudioThree,
        [Description("WD.RectangleGeometry")] Rectangle,
        [Description("WD.EllipseGeometry")] Ellipse,
        [Description("WD.UpperTriangleGeometry")] UpperTriangle,
        [Description("WD.ArrowGeometry")] Arrow,
        [Description("WD.ArrowRightTopGeometry")] ArrowRightTop,
        [Description("WD.ArrowBranchesGeometry")] ArrowBranches,
        [Description("WD.TextGeometry")] Text,
        [Description("WD.InkGeometry")] Ink,
        [Description("WD.StarSkyGeometry")] StarSky,
        [Description("WD.ReturnGeometry")] Return,
        [Description("WD.HomeGeometry")] Home,
        [Description("WD.UnfoldMoreGeometry")] UnfoldMore,
        [Description("WD.TimeGeometry")] Time,
        [Description("WD.DateRangeRightGeometry")] DateRangeRight,
        [Description("WD.DateGeometry")] Date,
        [Description("WD.CopyGeometry")] Copy,
    }
}
